name : CI pipeline

on:
  push:
    branches : 
      - feature/refactor-apps
  pull_request:

jobs:
  test-lint-build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install flake8 pytest

      - name: Lint with flake8 
        run: |
          echo "Running flake8 with setup.cfg"
          flake8 . 

      - name: Run tests with pytest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_KEY: ${{ secrets.SENTRY_KEY }}
        run: |
          echo "Running tests ..."
          pytest

      - name: Build Docker 
        run: |
          echo "Building Docker image..."
          docker build -t my-django-app .